WebApplication2/WebApplication2/Controllers/CRUDController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CRUDController : Controller
    {
        private Model1 db = new Model1();

        // GET: CRUD
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }


        // GET: CRUD/Create
        public ActionResult Create()
        {
            ViewBag.IDCategory = new SelectList(db.Categories, "IDCategory", "Category1");
            return View();
        }

        // POST: CRUD/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDProduct,IDCategory,Image,ProductName,Type,Unit,Amount,Price,Describe,Size,Season")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCategory = new SelectList(db.Categories, "IDCategory", "Category1", product.IDCategory);
            return View(product);
        }

        // GET: CRUD/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDCategory = new SelectList(db.Categories, "IDCategory", "Category1", product.IDCategory);
            return View(product);
        }

        // POST: CRUD/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDProduct,IDCategory,Image,ProductName,Type,Unit,Amount,Price,Describe,Size,Season")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDCategory = new SelectList(db.Categories, "IDCategory", "Category1", product.IDCategory);
            return View(product);
        }

        // GET: CRUD/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: CRUD/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/WebApplication2/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ProductController : Controller
    {
        Model1 db = new Model1();
        // GET: Product
        public ActionResult AllProduct()
        {
            List<Product> prolist = db.Products.ToList();
            return View(prolist);
        }
    }
}

WebApplication2/WebApplication2/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        Model1 db = new Model1();
        public ActionResult SearchProd(string keyword)
        {
            List<Product> product = db.Products.Where(s => s.ProductName.Contains(keyword)).ToList();
            return View(product);
        }
        [ChildActionOnly]
        public PartialViewResult SearchBox()
        {
            Product pro = new Product();
            string keyword = pro.ProductName;
            return PartialView(keyword);
            //return PartialView();
        }
    }
}

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication2/WebApplication2/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Tools Shop</title>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
    <link rel="stylesheet" type="text/css" href="~/style.css" />
    <!--[if IE 6]>
    <link rel="stylesheet" type="text/css" href="iecss.css" />
    <![endif]-->
    <script type="text/javascript" src="~/js/boxOver.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
</head>
<body>
    <div id="main_container">
        <div id="header">
            <div class="top_right">
                <div class="languages">
                    <div class="lang_text">Languages:</div>
                    <a href="http://all-free-download.com/free-website-templates/" class="lang"><img src="~/images/en.gif" alt="" border="0" /></a> <a href="http://all-free-download.com/free-website-templates/" class="lang"><img src="~/images/de.gif" alt="" border="0" /></a>
                </div>
            </div>
            <div id="logo"> <a href="http://all-free-download.com/free-website-templates/"><img src="~/images/logo.png" alt="" border="0" width="182" height="85" /></a> </div>
        </div>
        <div id="main_content">
            <div id="menu_tab">
                <ul class="menu">
                    <li><a href="@Url.Action("Index","Home")" class="nav"> Home </a></li>
                    <li class="divider"></li>
                    <li><a href="@Url.Action("AllProduct","Product")" class="nav">Products</a></li>
                    <li class="divider"></li>
                    <li><a href="@Url.Action("Register", "User")" class="nav">Sign Up</a></li>
                    <li class="divider"></li>
                    <li><a href="@Url.Action("Login", "User")" class="nav">Log In </a></li>
                    <li class="divider"></li>
                    <li><a href="@Url.Action("Contact", "About")" class="nav">Contact Us</a></li>
                    @if ((string)Session["user"] == "admin")
                    {
                        <li class="divider"></li>
                        <li><a href="@Url.Action("Index", "CRUD")" class="nav">Management</a></li>
                    }

                </ul>
            </div>
            <!-- end of menu tab -->
            <div class="crumb_navigation"> 
                @if (Session["user"] != null)
                {
                    <p>User: @Session["user"] @Html.ActionLink("Log out", "Logout", "User")</p> 
                }
                else
                {
                    <p>User: Guess</p>
                }
            </div> 
            <div class="left_content">
                <div class="title_box">Categories</div>


                @Html.Action("Category", "Home")





                <div class="title_box">Special Products</div>
                <div class="border_box">
                    <div class="product_title"><a href="http://all-free-download.com/free-website-templates/">Makita 156 MX-VL</a></div>
                    <div class="product_img"><a href="http://all-free-download.com/free-website-templates/"><img src="~/images/p1.jpg" alt="" border="0" /></a></div>
                    <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>
                </div>
                <div class="title_box">Newsletter</div>
                <div class="border_box">
                    <input type="text" name="newsletter" class="newsletter_input" value="your email" />
                    <a href="http://all-free-download.com/free-website-templates/" class="join">subscribe</a>
                </div>
                <div class="banner_adds"> <a href="http://all-free-download.com/free-website-templates/"><img src="~/images/bann2.jpg" alt="" border="0" /></a> </div>
            </div>
            <!-- end of left content -->
            @*<div class="center_content">*@
            @RenderBody()
            @*</div>*@
            <!-- end of center content -->
            <div class="right_content">
                <div class="title_box">Search</div>
                <div class="border_box">
                    @{ Html.RenderAction("SearchBox", "Search");}
                </div>
                <div class="shopping_cart">
                    <div class="title_box">Shopping cart</div>
                    @{Html.RenderAction("CartInfor", "Cart"); }
                    <div class="cart_icon"><a href="@Url.Action("Cart","Cart")"><img src="~/images/shoppingcart.png" alt="" width="35" height="35" border="0" /></a></div>
                </div>
                <div class="title_box">What’s new</div>
                <div class="border_box">
                    <div class="product_title"><a href="http://all-free-download.com/free-website-templates/">Motorola 156 MX-VL</a></div>
                    <div class="product_img"><a href="http://all-free-download.com/free-website-templates/"><img src="~/images/p2.jpg" alt="" border="0" /></a></div>
                    <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>
                </div>
                <div class="title_box">Manufacturers</div>
                <ul class="left_menu">
                    <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Bosch</a></li>
                    <li class="even"><a href="http://all-free-download.com/free-website-templates/">Samsung</a></li>
                    <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Makita</a></li>
                    <li class="even"><a href="http://all-free-download.com/free-website-templates/">LG</a></li>
                    <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Fujitsu Siemens</a></li>
                    <li class="even"><a href="http://all-free-download.com/free-website-templates/">Motorola</a></li>
                    <li class="odd"><a href="http://all-free-download.com/free-website-templates/">Phillips</a></li>
                    <li class="even"><a href="http://all-free-download.com/free-website-templates/">Beko</a></li>
                </ul>
                <div class="banner_adds"> <a href="http://all-free-download.com/free-website-templates/"><img src="~/images/bann1.jpg" alt="" border="0" /></a> </div>
            </div>
            <!-- end of right content -->
        </div>
        <!-- end of main content -->
        <div class="footer">
            <div class="left_footer"> <img src="~/images/footer_logo.png" alt="" width="89" height="42" /> </div>
            <div class="center_footer">
                Template name. All Rights Reserved 2008<br />
                <a href="http://csscreme.com"><img src="~/images/csscreme.jpg" alt="csscreme" title="csscreme" border="0" /></a><br />
                <img src="~/images/payment.gif" alt="" />
            </div>
            <div class="right_footer"> <a href="http://all-free-download.com/free-website-templates/">home</a> <a href="http://all-free-download.com/free-website-templates/">about</a> <a href="http://all-free-download.com/free-website-templates/">sitemap</a> <a href="http://all-free-download.com/free-website-templates/">rss</a> <a href="http://all-free-download.com/free-website-templates/">contact us</a> </div>
        </div>
    </div>
    <!-- end of main_container -->
    <div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div>
</body>
</html>